### ISSUE TITLE
How to use electric chuck in native C++?

### ISSUE THREAD

**Issue by bndcyan10** [DENSORobot/denso_cobotta_ros#22]
I am using the b-Cap Client library in native C++.
I tried to operate COBOTTA's electric chuck with the code below, but it didn't work. crush.
Please let me know where I am going wrong.
- Although it is not shown here, the arm can be operated.
- The electric chuck cannot be operated with HandMoveA and HandMoveH.HandChuck and HandUnChuck work.
- ManualResetPreparation and MotionPreparation have been executed.

```
#include "/bcap_core/bCAPClient/bcap_client.h"	// b-cap client libarary header
...

bool CobottaController_HandMoveH()
{
    HRESULT hr;
    BSTR bstr;
    VARIANT vntParam;
    VARIANT vntReturn;
    VARIANT* pvntData;

    bstr = SysAllocString(L"HandMoveH");

    VariantInit(&vntParam);
    VariantInit(&vntReturn);

    vntParam.vt = (VT_VARIANT|VT_ARRAY);
    vntParam.parray = SafeArrayCreateVector(VT_VARIANT, 0, 3);
    SafeArrayAccessData(vntParam.parray, (void**)&pvntData);

    pvntData[0].vt = VT_R8;
    pvntData[0].dblVal = 25;  // force [N]
    pvntData[1].vt = VT_BOOL;
    pvntData[1].bVal = VARIANT_TRUE;	// TRUE : close FALSE : open
    pvntData[2].vt = VT_BSTR;
    pvntData[2].bstrVal = SysAllocString(L"DetectOn");	// option

    SafeArrayUnaccessData(vntParam.parray);

    hr = bCap_ControllerExecute(fd, hCtrl, bstr, vntParam, &vntReturn);	// crush here

    sleep(2); // wait

    SysFreeString(bstr);
    VariantClear(&vntReturn);
    VariantClear(&vntParam);

    if ( SUCCEEDED(hr)) { return true; }
    else { return false; }

}
````

platfrom : windows11
compiler : MSVC 2022 community
b-Cap Client Library : build to static library with CMake(MSVC)

**Comment by furukawahiromi** [comment]
Sorry, this repository is for COBOTTA OSS type. Your COBOTTA is Standard type.

Please [email](fa-support@denso-wave.com) this issue with the error number and error message.
