### ISSUE TITLE
IOError : No such file or directory

### ISSUE THREAD

**Issue by hanggaga** [DENSORobot/denso_cobotta_ros#5]
On my terminal screen.
```
hanggaga@hanggaga-X555LB:~$ roslaunch denso_cobotta_moveit_config demo.launch 
... logging to /home/hanggaga/.ros/log/280c11ba-1311-11e9-a60d-40b89a4ff069/roslaunch-hanggaga-X555LB-20138.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/__init__.py", line 306, in main
    p.start()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/parent.py", line 268, in start
    self._start_infrastructure()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/parent.py", line 217, in _start_infrastructure
    self._load_config()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/parent.py", line 132, in _load_config
    roslaunch_strs=self.roslaunch_strs, verbose=self.verbose)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/config.py", line 451, in load_config_default
    loader.load(f, config, verbose=verbose)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 749, in load
    self._load_launch(launch, ros_config, is_core=core, filename=filename, argv=argv, verbose=verbose)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 721, in _load_launch
    self._recurse_load(ros_config, launch.childNodes, self.root_context, None, is_core, verbose)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 685, in _recurse_load
    val = self._include_tag(tag, context, ros_config, default_machine, is_core, verbose)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 95, in call
    return f(*args, **kwds)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 627, in _include_tag
    default_machine, is_core, verbose)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 665, in _recurse_load
    self._param_tag(tag, context, ros_config, verbose=verbose)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 95, in call
    return f(*args, **kwds)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 265, in _param_tag
    value = self.param_value(verbose, name, ptype, *vals)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/loader.py", line 472, in param_value
    with open(textfile, 'r') as f:
IOError: [Errno 2] No such file or directory: u'/home/suzuki/cobotta_description/cobotta.urdf'
```
File cobotta.urdf not found! .

**Comment by kamonpob** [comment]
Me too also.

**Comment by YoshihiroMIYAKOSHI** [comment]
Sorry, this repository is under developing.
Please wait for the official update.
We will announce the official update in this repository.

**Comment by ToshitakaSuzuki** [comment]
Sorry for confusing you..
As @YoshihiroMIYAKOSHI  mentioned, this repository is still under developing.
By the way, this repository is for controlling COBOTTA **OSS edition** from ROS.
If you try to control COBOTTA **standard edition** from ROS, please use [denso_robot_ros](https://github.com/DENSORobot/denso_robot_ros) packages and follow [these tutorials](http://wiki.ros.org/denso_robot_ros/Tutorials).

**Comment by bmunkhtulga** [comment]
> By the way, this repository is for controlling COBOTTA **OSS edition** from ROS.
> If you try to control COBOTTA **standard edition** from ROS, please use [denso_robot_ros](https://github.com/DENSORobot/denso_robot_ros) packages and follow [these tutorials](http://wiki.ros.org/denso_robot_ros/Tutorials).

How do I know which type of COBOTTA I am using? In documentation there was no indication of difference between OSS type and standard type?

**Comment by ToshitakaSuzuki** [comment]
> How do I know which type of COBOTTA I am using? In documentation there was no indication of difference between OSS type and standard type?
OSS type is not installed any OS when you bought.
So if your COBOTTA is OSS type, you should have installed Ubuntu to COBOTTA.

**Comment by bmunkhtulga** [comment]
> > How do I know which type of COBOTTA I am using? In documentation there was no indication of difference between OSS type and standard type?
> 
> OSS type is not installed any OS when you bought it.
> So if your COBOTTA is OSS type, you should have installed Ubuntu to COBOTTA.

When I unboxed COBOTTA, I was able to connect through Virtual Pendant (RC8) and WINCAPS III, does that mean it had OS (which means standard type)? Can I install OS by myself even it is standard type?

**Comment by ToshitakaSuzuki** [comment]
> When I unboxed COBOTTA, I was able to connect through Virtual Pendant (RC8) and WINCAPS III, does that mean it had OS (which means standard type)?

Yes. It means your COBOTTA is standard type.

> Can I install OS by myself even it is standard type?

No, you cannot change standard type to OSS type, and vice versa.
If you want to use ROS with standard type, please use [denso_robot_ros](https://github.com/DENSORobot/denso_robot_ros) packages.

**Comment by MRCSTJM** [comment]
> > When I unboxed COBOTTA, I was able to connect through Virtual Pendant (RC8) and WINCAPS III, does that mean it had OS (which means standard type)?
> 
> Yes. It means your COBOTTA is standard type.
> 
> > Can I install OS by myself even it is standard type?
> 
> No, you cannot change standard type to OSS type, and vice versa.
> If you want to use ROS with standard type, please use [denso_robot_ros](https://github.com/DENSORobot/denso_robot_ros) packages.

If the COBOTTA contains an X86 architecture, why can't I install linux to it just as I could do in a desktop? Are there any settings inside the COBOTTA to limit the type change? Thx!

**Comment by MRCSTJM** [comment]
I want to change the standard type to OSS type  even though this may result in void warranty. How can I do that? Thanks!
