### ISSUE TITLE
electric gripper control

### ISSUE THREAD

**Issue by sittikorn1904** [DENSORobot/denso_cobotta_ros#6]
How can I control electric gripper via bCAP? 
I try to use bCAP Extension to send command such as "Chuck", "UnChuck" but the robot tell me "Unknown name".

**Comment by ToshitakaSuzuki** [comment]
Sorry for the delayed response.
Is your COBOTTA OSS edition?
This repository is for controlling COBOTTA **OSS edition** from ROS.
